name: DeepQNetwork
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python==3.10.4
  - pytorch==2.0.1
  - jupyter 
  - click
  - Sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  - pip 